# Generated by Django 2.2.16 on 2020-10-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owen_num', models.IntegerField(verbose_name='生产数量')),
                ('status', models.SmallIntegerField(choices=[(2, '生产中'), (4, '订单完成'), (3, '待发货'), (1, '备料')], default=1, verbose_name='生产状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='生产订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='生产人员')),
            ],
            options={
                'verbose_name': '所有生产信息',
                'verbose_name_plural': '所有生产信息',
                'db_table': 'product_list',
                'ordering': ['-created_time'],
            },
        ),
    ]
