# Generated by Django 2.2.16 on 2020-10-21 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20201021_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64, verbose_name='客户名称')),
                ('good', models.CharField(max_length=128, verbose_name='货品名称')),
                ('deliver_time', models.CharField(max_length=128, verbose_name='发货时间')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('status', models.SmallIntegerField(choices=[('PROD_PROD', '生产中'), ('PROD_MATE', '备料'), ('PROD_FINS', '订单完成'), ('PROD_DIST', '派单'), ('PROD_DELE', '待发货')], verbose_name='订单状态')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '生产信息',
                'verbose_name_plural': '生产信息',
                'db_table': 'product',
                'ordering': ['-created_time'],
            },
        ),
    ]
