# Generated by Django 2.2.16 on 2020-10-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '派单'), (5, '订单完成'), (3, '生产中'), (1, '备料'), (4, '待发货')], verbose_name='订单状态'),
        ),
    ]
