# Generated by Django 2.2.16 on 2020-10-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201026_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '生产中'), (5, '订单完成'), (4, '待发货'), (2, '派单'), (1, '备料')], default=1, verbose_name='订单状态'),
        ),
    ]
