# Generated by Django 2.2.16 on 2020-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201030_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '备料'), (4, '订单完成'), (2, '生产中'), (3, '待发货')], default=1, verbose_name='生产状态'),
        ),
    ]
