# Generated by Django 2.2.16 on 2020-11-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201103_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.Order', verbose_name='生产订单'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '备料'), (3, '待发货'), (2, '生产中'), (4, '订单完成')], default=1, verbose_name='生产状态'),
        ),
    ]
