# Generated by Django 2.2.16 on 2020-11-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '生产中'), (4, '订单完成'), (3, '待发货'), (1, '备料')], default=1, verbose_name='生产状态'),
        ),
    ]
