# Generated by Django 2.2.16 on 2020-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201106_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '生产中'), (3, '待发货'), (4, '订单完成'), (1, '备料')], default=1, verbose_name='生产状态'),
        ),
    ]
