# Generated by Django 2.2.16 on 2020-11-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201106_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '待发货'), (2, '生产中'), (1, '备料'), (4, '订单完成')], default=1, verbose_name='生产状态'),
        ),
    ]
