# Generated by Django 2.2.16 on 2020-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20201208_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '待发货'), (2, '生产中'), (1, '备料中'), (4, '订单完成')], default=1, verbose_name='生产状态'),
        ),
    ]
