# Generated by Django 2.2.16 on 2020-10-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='beiliao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='daifahuo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paidan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shengchanzhong',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wancheng',
        ),
    ]
