# Generated by Django 2.2.16 on 2020-11-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.SmallIntegerField(choices=[(1, '业务'), (2, '业务'), (3, '业务')], default=1, verbose_name='权限'),
        ),
    ]
