# Generated by Django 2.2.16 on 2020-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='power',
            field=models.SmallIntegerField(choices=[(1, '业务'), (4, '经理'), (2, '生产'), (3, '商务')], default=1, verbose_name='权限'),
        ),
    ]
