# Generated by Django 2.2.16 on 2020-12-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201204_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='power',
            field=models.SmallIntegerField(choices=[(1, '业务'), (2, '生产'), (4, '经理'), (3, '商务')], default=1, verbose_name='权限'),
        ),
    ]
