# Generated by Django 2.2.16 on 2020-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201208_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='power',
            field=models.SmallIntegerField(choices=[(1, '业务'), (4, '经理'), (3, '商务'), (2, '生产')], default=1, verbose_name='权限'),
        ),
    ]
