# Generated by Django 2.2.16 on 2020-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20201215_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='power',
            field=models.SmallIntegerField(choices=[(1, '业务'), (2, '生产'), (3, '商务'), (4, '经理')], default=1, verbose_name='权限'),
        ),
    ]
