# Generated by Django 2.2.16 on 2020-10-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64, verbose_name='客户名称')),
                ('good', models.CharField(max_length=128, verbose_name='产品名称')),
                ('deliver_time', models.CharField(max_length=128, verbose_name='预计发货时间')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('salesperson', models.CharField(max_length=64, verbose_name='业务姓名')),
                ('is_valid', models.BooleanField(default=True, verbose_name='订单是否存在')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '所有订单信息',
                'verbose_name_plural': '所有订单信息',
                'db_table': 'order_list',
                'ordering': ['-created_time'],
            },
        ),
    ]
