# Generated by Django 2.2.16 on 2020-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deliver',
            field=models.BooleanField(default=False, verbose_name='订单是否已完成'),
        ),
    ]
