# Generated by Django 2.2.16 on 2020-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='料号信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='sn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(max_length=128, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_time',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='预计发货时间'),
        ),
    ]
