# Generated by Django 2.2.16 on 2020-11-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201106_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='sumnumber',
        ),
    ]
