# Generated by Django 2.2.16 on 2020-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201106_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_deliver',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, '生产中'), (1, '待生产'), (3, '待发货')], default=1, verbose_name='订单状态'),
        ),
    ]
