# Generated by Django 2.2.16 on 2020-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201203_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='number',
            new_name='good_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(4, '待发货'), (3, '生产中'), (2, '待生产'), (1, '备料中')], default=2, verbose_name='订单状态'),
        ),
    ]
