# Generated by Django 2.2.16 on 2020-12-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20201203_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(3, '生产中'), (2, '待生产'), (4, '待发货'), (1, '备料中')], default=2, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sn',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='订单编号'),
            preserve_default=False,
        ),
    ]
