# Generated by Django 2.2.16 on 2020-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201203_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sn',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, '待生产'), (3, '生产中'), (4, '待发货'), (1, '备料中')], default=2, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_list_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='配件单编号'),
        ),
    ]
