# Generated by Django 2.2.16 on 2020-12-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201203_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_id'], 'verbose_name': '所有订单信息', 'verbose_name_plural': '所有订单信息'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'ordering': ['list_id'], 'verbose_name': '订单配件表', 'verbose_name_plural': '订单配件表'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='id',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='list_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True, verbose_name='订单配件id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=11, primary_key=True, serialize=False, unique=True, verbose_name='订单编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(4, '待发货'), (3, '生产中'), (2, '待生产'), (1, '备料中')], default=2, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order_list_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单'),
            preserve_default=False,
        ),
    ]
