# Generated by Django 2.2.16 on 2020-12-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20201204_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_list_id',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.Order', verbose_name='订单'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(4, '待发货'), (3, '生产中'), (1, '备料中'), (2, '待生产')], default=2, verbose_name='订单状态'),
        ),
    ]
