# Generated by Django 2.2.16 on 2020-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20201207_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-28 17:45:17', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, '待生产'), (3, '生产中'), (1, '备料中'), (4, '待发货')], default=2, verbose_name='订单状态'),
        ),
    ]
