# Generated by Django 2.2.16 on 2020-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20201208_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(2, '生产中'), (4, '订单完成'), (3, '待发货'), (1, '待生产')], default=1, verbose_name='订单状态'),
        ),
    ]
