# Generated by Django 2.2.16 on 2020-12-15 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20201215_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '待生产'), (3, '待发货'), (4, '订单完成'), (2, '生产中')], default=1, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='物流单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbill', to='order.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '物流单号表',
                'verbose_name_plural': '物流单号表',
                'db_table': 'order_bill',
                'ordering': ['-create_time'],
            },
        ),
    ]
